package sprint

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CacheBundleSection names a single concatenated source. Output preserves
// section order so identical bundles produce byte-identical output across
// invocations — important for prompt-caching prefix stability.
type CacheBundleSection struct {
	Anchor string // h1/h2 heading written into the bundle ("## architecture.md")
	Path   string // source file path (relative to docs_folder or absolute)
}

// DefaultCacheBundleSections is the standing corpus a v6 hydrator typically
// needs: architecture + audit (+ supplement) + decision tree + saga mapping.
// Tunable per project by passing a different slice to BuildCacheBundle.
//
// Order matters — keep it stable across sprints so the bundle's prefix is
// byte-identical on every regeneration (gives Claude's auto-prompt-cache
// a hit point when the bundle is included in every hydrator dispatch).
var DefaultCacheBundleSections = []CacheBundleSection{
	{Anchor: "architecture.md", Path: "architecture.md"},
	{Anchor: "eda-cutover-decision-tree-2026-05-15.md", Path: "eda-cutover-decision-tree-2026-05-15.md"},
	{Anchor: "bc-boundary-audit-2026-05-15.md", Path: "bc-boundary-audit-2026-05-15.md"},
	{Anchor: "bc-boundary-audit-supplement-2026-05-15.md", Path: "bc-boundary-audit-supplement-2026-05-15.md"},
	{Anchor: "saga-to-slice-mapping-2026-05-15.md", Path: "saga-to-slice-mapping-2026-05-15.md"},
}

// BundleResult summarises what BuildCacheBundle wrote.
type BundleResult struct {
	OutPath        string   `json:"out_path"`
	IncludedFiles  []string `json:"included_files"`
	MissingFiles   []string `json:"missing_files,omitempty"`
	TotalBytes     int64    `json:"total_bytes"`
	GeneratedAt    string   `json:"generated_at"`
}

// BuildCacheBundle concatenates each section's source file into outPath
// with anchor headings + a deterministic generated-at footer. Missing
// files are skipped (not an error) and surfaced in MissingFiles so the
// caller can verify intent.
//
// Why deterministic: the bundle becomes the leading content of every
// stage_hydrate render. If two invocations produce byte-identical
// bundles, Claude Code's auto-prompt-caching can hit on subsequent
// hydrator dispatches in the same session.
func BuildCacheBundle(docsFolder, outPath string, sections []CacheBundleSection) (*BundleResult, error) {
	if outPath == "" {
		return nil, errors.New("cache bundle: outPath required")
	}
	if len(sections) == 0 {
		sections = DefaultCacheBundleSections
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return nil, fmt.Errorf("cache bundle: mkdir %s: %w", filepath.Dir(outPath), err)
	}

	out, err := os.Create(outPath)
	if err != nil {
		return nil, fmt.Errorf("cache bundle: create %s: %w", outPath, err)
	}
	defer out.Close()

	res := &BundleResult{OutPath: outPath}

	// Header — note this is the only non-deterministic part (timestamp).
	// Keep it at the END so the byte-identical prefix is the concatenated
	// content. Adjust if Claude's cache hashing semantics change.
	header := "# BMad v6 sprint cache bundle\n\n" +
		"Auto-generated by `bmad sprint cache-bundle`. The L3 hydrator " +
		"reads this single file instead of the individual sources below " +
		"— one file read per dispatch instead of " + fmt.Sprintf("%d", len(sections)) +
		". Stable across sprints to maximize prompt-cache prefix hits.\n\n"
	if _, err := out.WriteString(header); err != nil {
		return nil, fmt.Errorf("cache bundle: write header: %w", err)
	}

	for _, sec := range sections {
		full := sec.Path
		if !filepath.IsAbs(full) {
			full = filepath.Join(docsFolder, sec.Path)
		}
		raw, err := os.ReadFile(full)
		if errors.Is(err, os.ErrNotExist) {
			res.MissingFiles = append(res.MissingFiles, sec.Path)
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("cache bundle: read %s: %w", full, err)
		}

		// Anchor heading + content. Use `\n\n---\n\n` separators so
		// markdown viewers can navigate; agents grep by anchor.
		if _, err := fmt.Fprintf(out, "\n\n---\n\n## %s\n\nSource: `%s`\n\n%s",
			sec.Anchor, sec.Path, strings.TrimRight(string(raw), "\n")+"\n"); err != nil {
			return nil, fmt.Errorf("cache bundle: write section %s: %w", sec.Path, err)
		}
		res.IncludedFiles = append(res.IncludedFiles, sec.Path)
	}

	// Footer with generated-at — last bytes; doesn't affect the
	// deterministic-prefix part above.
	res.GeneratedAt = time.Now().UTC().Format(time.RFC3339)
	if _, err := fmt.Fprintf(out, "\n\n---\n\n_Generated at %s. Re-run `bmad sprint cache-bundle` to refresh._\n",
		res.GeneratedAt); err != nil {
		return nil, fmt.Errorf("cache bundle: write footer: %w", err)
	}

	if info, err := os.Stat(outPath); err == nil {
		res.TotalBytes = info.Size()
	}
	return res, nil
}
