package sprint

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// StoryContextSources is the inputs BuildStoryContext reads from. Optional
// paths are skipped when empty; their sections won't appear in the bundle.
type StoryContextSources struct {
	StoryID           string
	EpicsPath         string // required — the lightweight story entry is the bundle's seed
	ArchitecturePath  string // optional — FR refs in the entry trigger section extraction here
}

// StoryContextBundle summarises a BuildStoryContext run.
type StoryContextBundle struct {
	StoryID    string   `json:"story_id"`
	OutPath    string   `json:"out_path"`
	Sections   []string `json:"sections"`
	TotalBytes int64    `json:"total_bytes"`
	Warnings   []string `json:"warnings,omitempty"`
	GeneratedAt string  `json:"generated_at"`
}

// frRefRE matches Functional-Requirement reference anchors like FR-Arch-7,
// FR-NFR-12, FR-Saga-1, etc. Greedy on the kind so multi-word kinds
// (e.g., FR-Arch-XYZ) still capture.
var frRefRE = regexp.MustCompile(`FR-[A-Za-z]+-\d+`)

// BuildStoryContext extracts a curated per-story context bundle:
//
//   1. The story's lightweight entry from epics.md (extracted by section header)
//   2. For each FR-ref found in the entry: the matching section from
//      architecture.md (header line containing the ref + body until next ##/###)
//
// Output is a single self-contained markdown file. Deterministic across
// runs given identical inputs — supports byte-stable prefix for caching.
//
// Deliberately lean: doesn't try to extract BC audit rows or saga
// participation (those require knowing bc_target / slice, which is only
// reliable post-hydrate; this bundle is meant to land pre-hydrate so the
// hydrator has the smallest useful starting context).
func BuildStoryContext(outPath string, sources StoryContextSources) (*StoryContextBundle, error) {
	if sources.StoryID == "" {
		return nil, errors.New("story context: StoryID required")
	}
	if sources.EpicsPath == "" {
		return nil, errors.New("story context: EpicsPath required")
	}
	if outPath == "" {
		return nil, errors.New("story context: outPath required")
	}

	entry, err := extractStorySection(sources.EpicsPath, sources.StoryID)
	if err != nil {
		return nil, fmt.Errorf("story context: extract entry: %w", err)
	}
	if entry == "" {
		return nil, fmt.Errorf("story context: story %q not found in %s", sources.StoryID, sources.EpicsPath)
	}

	bundle := &StoryContextBundle{
		StoryID:  sources.StoryID,
		OutPath:  outPath,
		Sections: []string{"epics.md story entry"},
	}

	// Render the bundle into outPath.
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return nil, fmt.Errorf("story context: mkdir: %w", err)
	}
	out, err := os.Create(outPath)
	if err != nil {
		return nil, fmt.Errorf("story context: create %s: %w", outPath, err)
	}
	defer out.Close()

	// Header — small, deterministic.
	header := fmt.Sprintf("# Story %s — context bundle\n\n"+
		"Auto-generated by `bmad story context-bundle %s`. The L3 hydrator "+
		"(or any stage agent) reads this single file as its primary context; "+
		"the standing-corpus sections quoted below are pre-extracted by "+
		"deterministic Go code — no need to grep architecture.md at runtime.\n",
		sources.StoryID, sources.StoryID)
	if _, err := out.WriteString(header); err != nil {
		return nil, fmt.Errorf("story context: write header: %w", err)
	}

	// Section 1: story entry from epics.md.
	if _, err := fmt.Fprintf(out, "\n\n---\n\n## Lightweight story entry\n\nSource: `%s`\n\n%s\n",
		sources.EpicsPath, strings.TrimRight(entry, "\n")); err != nil {
		return nil, fmt.Errorf("story context: write entry: %w", err)
	}

	// Section 2: FR-ref-driven architecture extracts (if architecture path supplied).
	frRefs := uniqueOrdered(frRefRE.FindAllString(entry, -1))
	if sources.ArchitecturePath != "" && len(frRefs) > 0 {
		extracts, missing, err := extractArchSectionsForFRs(sources.ArchitecturePath, frRefs)
		if err != nil {
			bundle.Warnings = append(bundle.Warnings,
				fmt.Sprintf("architecture scan: %v", err))
		}
		for _, fr := range frRefs {
			body, ok := extracts[fr]
			if !ok {
				continue
			}
			if _, err := fmt.Fprintf(out, "\n\n---\n\n## Architecture section for %s\n\nSource: `%s`\n\n%s\n",
				fr, sources.ArchitecturePath, strings.TrimRight(body, "\n")); err != nil {
				return nil, fmt.Errorf("story context: write arch section %s: %w", fr, err)
			}
			bundle.Sections = append(bundle.Sections, "architecture.md section for "+fr)
		}
		for _, fr := range missing {
			bundle.Warnings = append(bundle.Warnings,
				fmt.Sprintf("FR ref %s referenced in entry but no matching architecture section found", fr))
		}
	} else if sources.ArchitecturePath == "" {
		bundle.Warnings = append(bundle.Warnings, "no ArchitecturePath provided — skipped FR-ref extraction")
	}

	// Footer with generated-at — last bytes; doesn't affect the
	// deterministic-prefix part above.
	bundle.GeneratedAt = time.Now().UTC().Format(time.RFC3339)
	if _, err := fmt.Fprintf(out, "\n\n---\n\n_Generated at %s. Re-run `bmad story context-bundle %s` to refresh._\n",
		bundle.GeneratedAt, sources.StoryID); err != nil {
		return nil, fmt.Errorf("story context: write footer: %w", err)
	}

	if info, err := os.Stat(outPath); err == nil {
		bundle.TotalBytes = info.Size()
	}
	return bundle, nil
}

// extractStorySection scans epics.md, finds `### Story <id>:` (or `### Story <id> -`),
// and returns every line up to the next `### ` header (or EOF). Matching is
// strict on the id (no prefix matches) to avoid grabbing 1.10 when looking
// for 1.1.
func extractStorySection(epicsPath, storyID string) (string, error) {
	f, err := os.Open(epicsPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// Match `### Story <id>:` or `### Story <id> -` exactly.
	headerRE := regexp.MustCompile(`^###\s+Story\s+` + regexp.QuoteMeta(storyID) + `\s*[:\-]`)

	scan := bufio.NewScanner(f)
	scan.Buffer(make([]byte, 1<<20), 1<<20)

	var (
		out      strings.Builder
		inStory  bool
	)
	for scan.Scan() {
		line := scan.Text()
		if headerRE.MatchString(line) {
			inStory = true
			out.WriteString(line)
			out.WriteString("\n")
			continue
		}
		if inStory {
			// Stop on the next ### header (any story / section).
			if strings.HasPrefix(line, "### ") || strings.HasPrefix(line, "## ") {
				break
			}
			out.WriteString(line)
			out.WriteString("\n")
		}
	}
	if err := scan.Err(); err != nil {
		return "", err
	}
	return out.String(), nil
}

// extractArchSectionsForFRs scans architecture.md for sections whose header
// line mentions any of the FR refs. Returns a map of ref -> section body
// and a list of refs that were searched-for but not found.
//
// "Section" here = the matching header line + everything until the next
// header at the same depth or shallower (e.g., a `### FR-Arch-7 — Foo`
// section ends at the next `###` or `##` or `#`).
func extractArchSectionsForFRs(archPath string, refs []string) (map[string]string, []string, error) {
	f, err := os.Open(archPath)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()

	want := make(map[string]bool, len(refs))
	for _, r := range refs {
		want[r] = true
	}

	results := make(map[string]string, len(refs))

	scan := bufio.NewScanner(f)
	scan.Buffer(make([]byte, 1<<20), 1<<20)

	var (
		currentRef   string
		currentDepth int  // number of leading # chars on the active section's header
		buf          strings.Builder
	)
	flush := func() {
		if currentRef == "" {
			return
		}
		results[currentRef] = buf.String()
		buf.Reset()
		currentRef = ""
		currentDepth = 0
	}

	for scan.Scan() {
		line := scan.Text()
		depth := countLeadingHash(line)
		if depth > 0 {
			// Header line — check if it starts a section we want.
			matched := ""
			for ref := range want {
				if strings.Contains(line, ref) {
					matched = ref
					break
				}
			}
			// If we hit a new header at a depth <= currentDepth, the
			// previous section ends.
			if currentRef != "" && depth <= currentDepth {
				flush()
			}
			if matched != "" && results[matched] == "" {
				currentRef = matched
				currentDepth = depth
				buf.WriteString(line)
				buf.WriteString("\n")
				continue
			}
		}
		if currentRef != "" {
			buf.WriteString(line)
			buf.WriteString("\n")
		}
	}
	flush()
	if err := scan.Err(); err != nil {
		return nil, nil, err
	}

	var missing []string
	for _, r := range refs {
		if _, ok := results[r]; !ok {
			missing = append(missing, r)
		}
	}
	return results, missing, nil
}

// countLeadingHash returns the count of leading # chars (markdown header depth);
// 0 if the line is not a header.
func countLeadingHash(line string) int {
	n := 0
	for n < len(line) && line[n] == '#' {
		n++
	}
	if n == 0 || n >= len(line) || line[n] != ' ' {
		return 0
	}
	return n
}

// uniqueOrdered de-duplicates while preserving first-seen order.
func uniqueOrdered(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}
