-- Migration 0003 — idempotency keys + atomic story claim.
--
-- Idempotency keys (dispatches + checkpoints):
--   Generated by the orchestrator BEFORE invoking an L3 agent (dispatches)
--   or before firing a checkpoint (checkpoints). Recorded in the row upfront
--   with status=dispatched / decision=NULL. On crash resume the orchestrator
--   scans for rows in those states and reconciles instead of double-dispatching.
--
--   Partial unique indexes (WHERE key IS NOT NULL) let pre-key historical
--   rows remain. Going forward, every dispatched/fired row carries a key.
--
-- Atomic story claim (stories + audit columns):
--   `bmad story next --claim` atomically picks pending stories AND marks them
--   claimed in one transaction, so two orchestrator iterations (or two
--   orchestrator processes) can never both pick the same story. Adds
--   `claimed_at` + `claimed_by` so we can see who's holding what.

-- ---------- Dispatches: idempotency key ----------
ALTER TABLE dispatches ADD COLUMN idempotency_key TEXT;
CREATE UNIQUE INDEX dispatches_idempotency_key_uniq
  ON dispatches(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ---------- Checkpoints: idempotency key ----------
ALTER TABLE checkpoints ADD COLUMN idempotency_key TEXT;
CREATE UNIQUE INDEX checkpoints_idempotency_key_uniq
  ON checkpoints(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ---------- Stories: claim audit ----------
ALTER TABLE stories ADD COLUMN claimed_at TIMESTAMP;
ALTER TABLE stories ADD COLUMN claimed_by TEXT;
